### PR TITLE
Update oss-survey-chinese.txt

### PR DESCRIPTION
**Pull request by PeterDaveHello**
This update is basically based on my background, knowledge and experience, but I have concern about using a single "Chinese" to cover all the Chinese types, since there are so many different in characters and terms in different Chinese,  not to make the case so complex, we can simply category the Chinese translation into **Traditional Chinese**(zh-Hant) and **Simplified Chinese**(zh-Hant),  for a deeper look, `zh-tw`, `zh-cn`, `zh-hk` may be the most common seen Chinese types, there are also `zh-mo`, `zh-sg` and others, I'm not sure which one is this survey translation. I know that GitHub is banned in the mainland China, so maybe it's the reason why there is no Simplified Chinese? 

Just FYI, maybe the Wiki page about Chinese Wikipedia can be a reference about different Chinese:
https://en.wikipedia.org/wiki/Chinese_Wikipedia

By the way, about Q31/32, the terms, IMO, the translation of "Harassment over a sustained period" and "Stalking" could be very similar, I can't even directly recognize the different between them, maybe need more discussion.

--
cc #47

### CODE REVIEW

**Comment by bkeepers** [comment]
Hey @PeterDaveHello, thanks for the updates!

> … I have concern about using a single "Chinese" to cover all the Chinese types, since there are so many different in characters and terms in different Chinese

My mistake for not clarifying that the current translation is _Traditional Chinese_, which we chose based on number of visitors to GitHub.com. We can definitely consider adding a Simplified Chinese translation next time we run the survey, but we won't be able to add it for this iteration.

Do you know anyone who is fluent in Traditional Chinese?

**Comment by PeterDaveHello** [comment]
@bkeepers I think I'm fluent in Traditional Chinese :smile:

**Comment by bkeepers** [comment]
> Do you know anyone who is fluent in Traditional Chinese?

Sorry, I just saw your comment here: https://github.com/github/open-source-survey/issues/47#issuecomment-273432975

I'd love to find another person that can work with you to review this. Any recommendations?

**Comment by PeterDaveHello** [comment]
@bkeepers yes, @appleboy is a famous FOSS contributor/developer in Taiwan, I'll like to invite him help review with respect.

Hi @appleboy, would you like to take a look at the translation changes? Thanks a lot!

**Comment by appleboy** [comment]
LGTM

**Comment by bkeepers** [comment]
Thanks for your help!

**Pull request merged**
