### PR TITLE
Corrections to russian translation

### PR DESCRIPTION
**Pull request by zafarella**
* corrections to translation

Relates to #47

### CODE REVIEW

**Comment by bkeepers** [comment]
Hey @zafarella, thanks for the corrections! I'd like to get another set of :eyes: on this.

@annafil I know you were reviewing the Russian translation. Your feedback here would be _much_ appreciated!

**Comment by bkeepers** [comment]
Hey @zafarella, thanks for all your hard work here! We merged #55 since it has some detailed explanations about what changed and why.

If you have any suggestions for #55, or any changes here that should still be considered, please let us know!

**Comment by zafarella** [comment]
sure, np.

Anna as I got was referring to her PR as addition this one.

I can add comments for reasons of changes as github comments, if that works. 
The correction I made still should be helpful/valid.

@bkeepers ^

**Comment by bkeepers** [comment]
> I can add comments for reasons of changes as github comments, if that works.

A new PR based off master would be great!

**Comment by annafil** [comment]
I saw @zafarella 's PR too and think the suggestions made there are all on point and as far as I can tell there isn't significant overlap, but happy to chat more in the PR comments if there might be. It's probably relatively minor

**Pull request closed without merging**
